image: node:14.18.0-alpine

before_script:
  - npm i -g firebase-tools @angular/cli@10.1.3

variables:
  ENVIRONMENT_FILE_CONTENT: $ENVIRONMENT_FILE_PROD
  AUTHFLOW_FILE_CONTENT: $AUTHFLOW_FILE_PROD
  PARAMS_FILE_CONTENT: $PARAMS_FILE_PROD

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
      - dist/
  environment:
    name: production
  script:
    - npm i
    - npm run config "--environment=production"
    - ng build "--configuration=production"
  only:
    refs:
      - master

deploy:
  stage: deploy
  cache:
    paths:
      - dist/
  environment:
    name: production
  script:
    - firebase deploy --project prod --token $FIREBASE_TOKEN
  only:
    refs:
      - master
