image: node:12.18-stretch-slim

before_script:
  - npm i -g firebase-tools@10.6.0 @angular/cli@10.1.3

variables:
  ENVIRONMENT_FILE_CONTENT: $ENVIRONMENT_FILE_DEV
  AUTHFLOW_FILE_CONTENT: $AUTHFLOW_FILE_DEV
  PARAMS_FILE_CONTENT: $PARAMS_FILE_DEV

stages:
  - build
  - deploy


build:
  stage: build
  cache:
    paths:
      - node_modules/
      - dist/
  environment:
    name: staging
  script:
    - npm i
    - npm run config "--environment=dev"
    - ng build "--configuration=dev"
  only:
    refs:
      - develop

deploy:
  stage: deploy
  cache:
    paths:
      - dist/
  environment:
    name: staging
  script:
    - firebase deploy --project dev --token $FIREBASE_TOKEN
  only:
    refs:
      - develop
