image:
  name: node:20.9-alpine

variables:
  ENVIRONMENT_FILE_CONTENT: $ENVIRONMENT_FILE
  AUTHFLOW_FILE_CONTENT: $AUTHFLOW_FILE
  PARAMS_FILE_CONTENT: $PARAMS_FILE

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
      - dist/
  environment:
    name: production
  script:
    - echo test
    - npm i
    - echo test2
    - npm run config "--environment=production"
    - echo test3
    - ng build "--configuration=production"
    - echo test4
  only:
    refs:
      - master

deploy:
  stage: deploy
  cache:
    paths:
      - dist/
  environment:
    name: production
  script:
    - firebase deploy --project prod --token $FIREBASE_TOKEN
  only:
    refs:
      - master
