image: node:alpine

stages:
  - test
  - build
  - deploy

test:
  image: weboaks/node-karma-protractor-chrome:alpine
  stage: test
  before_script:
    - npm i
    - ls -la /usr/local/lib/node_modules
    - id -un
  cache:
    paths:
      - node_modules/
  environment:
    name: staging
    url: https://pole-emploi-trad-dev.firebaseapp.com
  script:
    - npm run config "--environment=dev"
    - npm run test
  only:
    refs:
      - develop

build:
  stage: build
  cache:
    paths:
      - node_modules/
      - dist/

  script:
    - npm run config "--environment=dev"
    - npm run build "--configuration=dev"

deploy:
  stage: deploy
  before_script:
    - npm i -g firebase-tools
  cache:
    paths:
      - dist/
  environment:
    name: staging
    url: https://pole-emploi-trad-dev.firebaseapp.com
  script:
    - firebase deploy --project dev --token $FIREBASE_TOKEN
  only:
    refs:
      - develop
