image:
  name: node:20.9-alpine

before_script:
  - npm i -g firebase-tools@10.6.0 @angular/cli@10.1.3
  - npm ci
  - npm install @angular/material @angular/cdk @angular/animations

variables:
  ENVIRONMENT_FILE_CONTENT: $ENVIRONMENT_FILE_OPEN_SOURCE
  AUTHFLOW_FILE_CONTENT: $AUTHFLOW_FILE_OPEN_SOURCE
  PARAMS_FILE_CONTENT: $PARAMS_FILE_OPEN_SOURCE

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
      - dist/
  environment:
    name: open-source
  script:
    - npm i --force
    - npm run config "--environment=open-source"
    - ng build "--configuration=open-source"
  only:
    refs:
      - master

deploy:
  stage: deploy
  cache:
    paths:
      - dist/
  environment:
    name: open-source
  script:
    - firebase deploy --project pole-emploi-trad-open --token $FIREBASE_TOKEN
  only:
    refs:
      - master
