image: node:12.18-stretch-slim

before_script:
  - npm i -g firebase-tools @angular/cli@8.1.2

stages:
  - deploy

deploy:
    stage: deploy
    environment:
        name: staging
        url: https://pole-emploi-trad-dev.firebaseapp.com
    script:
        - npm install
        - npm run config "--environment=dev" && ng build "--configuration=dev"
        - firebase projects:list
        - firebase use pole-emploi-trad-summer
        - firebase deploy --token $FIREBASE_TOKEN
    only:
      refs:
        - securing_api_keys
