image: node:12.18-stretch-slim

before_script:
  - npm i -g firebase-tools @angular/cli@8.1.2

stages:
  - - build
  - build
  - deploy

test:
  before_script:
    - npm i
  image: trion/ng-cli-karma
  allow_failure: true
  stage: test
  cache:
    paths:
      - node_modules/
  environment:
    name: staging
    url: https://pole-emploi-trad-dev.firebaseapp.com
  script:
    - npm run config "--environment=dev"
    - ng test --progress false --watch false
  only:
    refs:
      - securing_api_keys
  artifacts:
    when: always
    reports:
      junit: report.xml


build:
  stage: build
  before_script:
    - npm i
  cache:
    paths:
      - node_modules/
      - dist/
  environment:
    name: staging
    url: https://pole-emploi-trad-dev.firebaseapp.com
  script:
    - npm run config "--environment=dev"
    - ng build "--configuration=dev"
  only:
    refs:
      - develop

deploy:
  stage: deploy
  cache:
    paths:
      - dist/
  environment:
    name: staging
    url: https://pole-emploi-trad-dev.firebaseapp.com
  script:
    - firebase deploy --project dev --token $FIREBASE_TOKEN
  only:
    refs:
      - develop
