image: node:alpine

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - npm i
  cache:
    paths:
      - node_modules/
      - dist/

  script:
    - npm run config "--environment=dev"
    - npm run build "--configuration=dev"

deploy:
  stage: deploy
  before_script:
    - npm i -g firebase-tools
  cache:
    paths:
      - dist/
  environment:
    name: staging
    url: https://pole-emploi-trad-dev.firebaseapp.com
  script:
    - firebase deploy --project dev --token $FIREBASE_TOKEN
  only:
    refs:
      - develop
