image: node:12.18-stretch-slim

before_script:
  - npm i -g firebase-tools @angular/cli@8.1.2

variables:
  ENVIRONMENT_FILE_CONTENT: $ENVIRONMENT_FILE_PROD
  AUTHFLOW_FILE_CONTENT: $AUTHFLOW_FILE_PROD

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
      - dist/
  environment:
    name: production
    url: https://pole-emploi-trad-prod.firebaseapp.com
  script:
    - npm i
    - npm run config "--environment=production"
    - ng build "--configuration=production"
  only:
    refs:
      - master

deploy:
  stage: deploy
  cache:
    paths:
      - dist/
  environment:
    name: production
    url: https://pole-emploi-trad-prod.firebaseapp.com
  script:
    - firebase deploy --project prod --token $FIREBASE_TOKEN
  only:
    refs:
      - masetr
