image: node:alpine
before_script:
  - npm i -g firebase-tools
deploy-functions:
  stage: deploy
  script:
    - npm install
    - npm run build:dev
    - firebase deploy project:dev --token $FIREBASE_TOKEN 
  only:
    refs:
      - develop