image: node:16-alpine

before_script:
  - npm i -g firebase-tools @angular/cli@10.1.3

variables:
  ENVIRONMENT_FILE_CONTENT: $ENVIRONMENT_FILE_RECETTE
  AUTHFLOW_FILE_CONTENT: $AUTHFLOW_FILE_RECETTE

stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    - npm i
  image: trion/ng-cli-karma:10.0.2
  allow_failure: true
  cache:
    paths:
      - node_modules/
  environment:
    name: uat
    url: https://pole-emploi-trad-recette.firebaseapp.com
  script:
    - npm run config "--environment=qa"
    - ng test --progress false --watch false
  only:
    refs:
      - release
  artifacts:
    when: always
    reports:
      junit: report.xml

build:
  stage: build
  cache:
    paths:
      - node_modules/
      - dist/
  environment:
    name: uat
    url: https://pole-emploi-trad-recette.firebaseapp.com
  script:
    - npm i
    - npm run config "--environment=qa"
    - ng build "--configuration=qa"
  only:
    refs:
      - release

deploy:
  stage: deploy
  cache:
    paths:
      - dist/
  environment:
    name: uat
    url: https://pole-emploi-trad-recette.firebaseapp.com
  script:
    - firebase deploy --project qa --token $FIREBASE_TOKEN
  only:
    refs:
      - release
