image: node:12.18-stretch-slim

before_script:
  - npm i -g firebase @angular/cli@8.1.2

stages:
  - deploy

deploy:
    stage: deploy
    environment:
        name: staging
        url: https://pole-emploi-trad-dev.firebaseapp.com
    script:
        npm install
        npm run config "--environment=dev" && ng build "--configuration=dev"
        firebase deploy --project dev --token 4/1AX4XfWjF958hss5mY8MQtkUVRNAHaXq2tL2BWo39x56L6ms2dgo7Cg8F15A
    only:
      refs:
        - securing_api_keys
