image: node:12.18-stretch-slim

before_script:
  - npm i -g firebase-tools

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    paths:
      - node_modules/
      - dist/
  environment:
    name: staging
    url: https://pole-emploi-trad-summer.firebaseapp.com
  script:
    - npm install
    - npm run config "--environment=dev"
    - ng build "--configuration=dev"
  only:
    refs:
      - securing_api_keys

deploy:
  stage: deploy
  cache:
    paths:
      - dist/
  environment:
    name: staging
    url: https://pole-emploi-trad-summer.firebaseapp.com
  script:
    - firebase deploy --project summer --token $FIREBASE_TOKEN
  only:
    refs:
      - securing_api_keys
